Added 'Missing Secure Coding' Validator
SkylineCommunications/Skyline.DataMiner.CICD.Validators pull request #110
Opened 2024-12-19 14:41 UTC by FlavioJA

2024-12-24 14:09 UTC, MichielOda requested changes

2024-12-24 14:09 UTC, MichielOda commented on Protocol/Tests/Protocol/QActions/CheckAssemblies.cs
> +                if (!project.PackageReferences.Any(package => package.Name.Equals("Skyline.DataMiner.Utils.SecureCoding", System.StringComparison.OrdinalIgnoreCase)))
Currently this will only check the SecureCoding NuGet and not the Analyzers.

2025-01-09 08:46 UTC, FlavioJA commented on Protocol/Error Messages/Protocol/QActions/CheckAssemblies.cs
> +                FixImpact = FixImpact.Undefined,
Done.

2025-01-09 08:46 UTC, FlavioJA commented on Protocol/Error Messages/Protocol/QActions/CheckAssemblies.cs
> +                Description = "Missing Skyline.DataMiner.Utils.SecureCoding Package.",
Done.

2025-01-09 08:47 UTC, FlavioJA commented on Protocol/Tests/Protocol/QActions/CheckAssemblies.cs
> +                if (!project.PackageReferences.Any(package => package.Name.Equals("Skyline.DataMiner.Utils.SecureCoding", System.StringComparison.OrdinalIgnoreCase)))
Changed the check to verify whether the Skyline.DataMiner.Utils.SecureCoding.Analyzers is present as discussed in the mail thread 'Secure Coding Validators in DIS'.

2025-01-13 12:35 UTC, MichielOda requested changes

2025-01-13 12:35 UTC, MichielOda commented on ProtocolTests/Protocol/QActions/CheckAssemblies/CheckAssemblies.cs
> +                    Error.MissingSecureCoding(null, null, null, null),
This fails the unit test. This needs to be filled in with the actual QAction ID

2025-01-13 12:35 UTC, MichielOda commented on Protocol/ErrorMessages.xml.bak
File is still present?

2025-01-13 12:35 UTC, MichielOda commented on Protocol/Error Messages/Protocol/QActions/CheckAssemblies.cs
> +                Description = "Missing Skyline.DataMiner.Utils.SecureCoding Package.",
With the recent change to only include the Analyzers, also update the description to mention the correct package.

2025-01-14 10:16 UTC, FlavioJA commented on Protocol/ErrorMessages.xml.bak
ErrorMessages.xml.bak file is now removed.

2025-01-14 10:16 UTC, FlavioJA commented on Protocol/Error Messages/Protocol/QActions/CheckAssemblies.cs
> +                Description = "Missing Skyline.DataMiner.Utils.SecureCoding Package.",
Done.

2025-01-14 10:24 UTC, FlavioJA commented on ProtocolTests/Protocol/QActions/CheckAssemblies/CheckAssemblies.cs
> +                    Error.MissingSecureCoding(null, null, null, null),
Done.

2025-01-22 08:26 UTC, MichielOda requested changes

2025-01-22 08:26 UTC, MichielOda commented on Protocol/Error Messages/Protocol/QActions/CheckAssemblies.cs
> +                Description = $"Missing Skyline.DataMiner.Utils.SecureCoding.Analyzers Package. QAction ID '{qactionId}'.",
Change was only done to the file and not via the Validator Management Tool. The next time someone will generate the errors, it will be overwritten by the previous description from the ErrorMessages.xml.

2025-02-03 13:57 UTC, MichielOda approved these changes

2025-02-03 13:58 UTC, merged