Validator tool dir creation and also accept input dir in addition to full sln file path
SkylineCommunications/Skyline.DataMiner.CICD.Validators pull request #26
Opened 2024-02-21 14:31 UTC by PedroDebevere

2024-02-21 14:57 UTC, MichielOda requested changes

2024-02-21 14:57 UTC, MichielOda commented on Skyline.DataMiner.CICD.Tools.Validator/ValidatorRunner.cs
> +            }
Maybe move this in a separate method

2024-02-21 14:57 UTC, MichielOda commented on Skyline.DataMiner.CICD.Tools.Validator/Program.cs
> +            var solutionPathOption = new Option<string>(
Why the change to allow folder paths?

2024-02-21 15:24 UTC, PedroDebevere commented on Skyline.DataMiner.CICD.Tools.Validator/ValidatorRunner.cs
> +            }
updated

2024-02-22 07:24 UTC, MichielOda approved these changes

2024-02-22 08:58 UTC, janstaelensskyline approved these changes

2024-02-22 09:02 UTC, merged